PresentationLayer/Controllers/CourseController.cs
using BusinessLogic;
using EntityLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PresentationLayer.Controllers
{
    public class CourseController : Controller
    {
        CourseLogic courseLogic = new CourseLogic();

        // GET: Course
        public ActionResult ListCourse()
        {
            return View(courseLogic.listCourse());
        }

        public ActionResult AddCourse()
        {
            List<TeacherEntity> listTeacher = new List<TeacherEntity>();
            TeacherLogic teacherLogic = new TeacherLogic();
            listTeacher = teacherLogic.listTeacher(); // Obtenemos la lista de todos los profesores
            ViewBag.ListTeachers = listTeacher; // Lo guardamos en un ViewBag

            return View();
        }

        public ActionResult InsertCourse(string cbxTeacher, string txtCourse)
        {
            CourseEntity course = new CourseEntity();
            course.teacher.id_teacher = Convert.ToInt32(cbxTeacher);
            course.course = txtCourse;

            String script = "";

            if (courseLogic.addCourse(course))
            {
                script = "<script languaje='javascript'>" +
                            "window.location.href='/Course/ListCourse'; " +
                         "</script>";
            }
            else
            {
                script = "<script languaje='javascript'>" +
                            "alert('Registro no agregado'); " +
                         "</script>";
            }

            return Content(script);
        }

        public ActionResult EditCourse(int id)
        {
            List<TeacherEntity> listTeacher = new List<TeacherEntity>();
            TeacherLogic teacherLogic = new TeacherLogic();
            listTeacher = teacherLogic.listTeacher(); // Obtenemos la lista de todos los profesores
            ViewBag.ListTeachers = listTeacher; // Lo guardamos en un ViewBag

            return View(courseLogic.searchTeacher(id));
        }

        public ActionResult UpdateCourse(string id, string txtCourse, string cbxTeacher)
        {
            CourseEntity course = new CourseEntity();
            course.id_course = Convert.ToInt32(id);
            course.teacher.id_teacher = Convert.ToInt32(cbxTeacher);
            course.course = txtCourse;

            String script = "";

            if (courseLogic.updateTeacher(course))
            {
                script = "<script languaje='javascript'>" +
                            "window.location.href='/Course/ListCourse'; " +
                            "</script>";
            }
            else
            {
                script = "<script languaje='javascript'>" +
                            "alert('Registro no actualizado'); " +
                            "</script>";
            }

            return Content(script);
        }
    }
}

PresentationLayer/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using EntityLayer;
using BusinessLogic;

namespace PresentationLayer.Controllers
{
    public class TeacherController : Controller
    {
        // GET: Teacher
        TeacherLogic teacherLogic = new TeacherLogic();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ListTeachers()
        {
            return View(teacherLogic.listTeacher());
        }

        // Método para ir al formulario
        public ActionResult AddTeachers()
        {
            return View();
        }

        // Método para recibir datos del formulario
        public ActionResult InsertTeacher(string txtFirst, string txtLast)
        {
            TeacherEntity teacher = new TeacherEntity();
            teacher.first = txtFirst;
            teacher.last = txtLast;

            String script = "";

            if (teacherLogic.addTeacher(teacher))
            {
                script = "<script languaje='javascript'>" +
                            "window.location.href='/Teacher/ListTeachers'; " +
                         "</script>";
            } else
            {
                script = "<script languaje='javascript'>" +
                            "alert('Registro no agregado'); " +
                         "</script>";
            }

            return Content(script);
        }

        public ActionResult EditTeacher(int id)
        {
            return View(teacherLogic.searchTeacher(id));
        }

        public ActionResult UpdateTeacher(string id, string txtFirst, string txtLast)
        {
            TeacherEntity teacher = new TeacherEntity();
            teacher.id_teacher = Convert.ToInt32(id);
            teacher.first = txtFirst;
            teacher.last = txtLast;

            String script = "";

            if (teacherLogic.updateTeacher(teacher))
            {
                script = "<script languaje='javascript'>" +
                            "window.location.href='/Teacher/ListTeachers'; " +
                            "</script>";
            } else
            {
                script = "<script languaje='javascript'>" +
                            "alert('Registro no actualizado'); " +
                            "</script>";
            }

            return Content(script);
        }
        
        public ActionResult DeleteTeacher(int idTeacher)
        {
            string script = "";

            if (teacherLogic.deleteTeacher(idTeacher))
            {
                script = "<script languaje='javascript'>" +
                            "window.location.href='/Teacher/ListTeachers'; " +
                         "</script>";
            }
            else
            {
                script = "<script languaje='javascript'>" +
                            "alert('No se pudo eliminar'); " +
                         "</script>";
            }

            return Content(script);
        }
    }
}

PresentationLayer/Views/Course/AddCourse.cshtml
@model EntityLayer.CourseEntity

@{
    ViewBag.Title = "AddCourse";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";

    var listTeachers = ViewBag.ListTeachers; // Llamamos al ViewBag de la lista
}

<h2>AddCourse</h2>

<div>
    @using (Html.BeginForm("InsertCourse", "Course", FormMethod.Post))
    {
        <input autofocus type="text" name="txtCourse" placeholder="Nombre del curso" /><br />
    
        <select name="cbxTeacher">
            @foreach (var item in listTeachers)
            {
                <option value="@item.id_teacher">@item.first @item.last</option>
            }
        </select>
        <br />
        <input type="submit" value="Registrar Curso" />
    }
</div>

PresentationLayer/Views/Course/EditCourse.cshtml
@model EntityLayer.CourseEntity

@{
    ViewBag.Title = "EditCourse";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";

    var listTeachers = ViewBag.ListTeachers; // Llamamos al ViewBag de la lista
}

<h2>EditCourse</h2>

<div>
    @using (Html.BeginForm("UpdateCourse", "Course", FormMethod.Post))
    {
        <input readonly type="number" value="@Model.id_course" name="id" /><br />
        <input autofocus type="text" value="@Model.course" name="txtCourse" placeholder="Nombre del curso" /><br />
        <input readonly type="text" value="@Model.teacher.fullname" placeholder="Nombre del Catedratico" /><br />

        <p>Cambiar Profesor:</p>
        <select name="cbxTeacher">
            @foreach (var item in listTeachers)
            {
                <option value="@item.id_teacher">@item.first @item.last</option>
            }
        </select>
        <br />
        <input type="submit" value="Actualizar Curso" />
    }
</div>

PresentationLayer/Views/Course/ListCourse.cshtml
<!-- Envolvemos el modelo en una lista -->
@model List<EntityLayer.CourseEntity>

@{
    ViewBag.Title = "ListCourse";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<h2>ListCourse</h2>

<table>
    <tr>
        <th>Identificador</th>
        <th>Nombre</th>
        <th>Catedrático</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.id_course</td>
            <td>@item.course</td>
            <td>@item.teacher.fullname</td>
            <td>@Html.ActionLink("Editar", "EditCourse", new { id = item.id_course })</td>
        </tr>
    }
</table>

PresentationLayer/Views/Layout/_LayoutMenu.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <ul>
        <li><a href="/Teacher/Index">Inicio</a></li>
        <li><a href="/Teacher/ListTeachers">Listado de Profesores</a></li>
        <li><a href="/Course/ListCourse">Listado de Cursos</a></li>
        <li><a href="/Teacher/AddTeachers">Agregar Profesores</a></li>
        <li><a href="/Course/AddCourse">Agregar Cursos</a></li>
    </ul>
    <div>
        @RenderBody()
    </div>
</body>
</html>

PresentationLayer/Views/Teacher/AddTeachers.cshtml
@model EntityLayer.TeacherEntity

@{
    ViewBag.Title = "AddTeachers";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<h2>AddTeachers</h2>

<div>
    @using (Html.BeginForm("InsertTeacher", "Teacher", FormMethod.Post)) // Envía datos al método del controlador
    {
        <input type="text" name="txtFirst" placeholder="Nombre" autofocus /><br />
        <input type="text" name="txtLast" placeholder="Apellido"/><br />
        <input type="submit" value="Registrar" /><br />
    }
</div>

PresentationLayer/Views/Teacher/EditTeacher.cshtml
@model EntityLayer.TeacherEntity

@{
    ViewBag.Title = "EditTeacher";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<h2>EditTeacher</h2>

<div>
    @using (Html.BeginForm("UpdateTeacher", "Teacher", FormMethod.Post))
    {
        <input readonly type="number" name="id" placeholder="Identificador" value="@Model.id_teacher" /><br />
        <input type="text" name="txtFirst" placeholder="Nombre" value="@Model.first" autofocus /><br />
        <input type="text" name="txtLast" placeholder="Apellido" value="@Model.last" /><br />
        <input type="submit" value="Actualizar" /><br />
    }
</div>

PresentationLayer/Views/Teacher/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<center>
    <h1>Index</h1>
</center>

<h2>Bienvenidos</h2>

PresentationLayer/Views/Teacher/listTeachers.cshtml
@model List<EntityLayer.TeacherEntity>

@{
    ViewBag.Title = "listTeachers";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<h2>listTeachers</h2>

<table>
    <tr>
        <th>Id</th>
        <th>Nombre</th>
        <th>Apellido</th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>@item.id_teacher</td>
        <td>@item.first</td>
        <td>@item.last</td>
        <td>@Html.ActionLink("Editar","EditTeacher", new { id = item.id_teacher })</td>
        <td>@Html.ActionLink("Eliminar", "DeleteTeacher", new { idTeacher = item.id_teacher })</td>
    </tr>
    }
</table>

PresentationLayer/Views/View.cshtml
@{
    ViewBag.Title = "View";
    Layout = "~/Views/Layout/_LayoutMenu.cshtml";
}

<h2>View</h2>

<p>Hola a todos</p>